export interface Project {
  id: string
  name: string
  description?: string
  created_at: string
  updated_at: string
  status: "exploring" | "modeling" | "deployed"
}

export interface ColumnStat {
  name: string
  dtype: string
  non_null_count: number
  null_count: number
  null_pct: number
  unique_count: number
  min?: number | null
  max?: number | null
  mean?: number | null
  std?: number | null
  sample_values: (string | number | null)[]
  distribution?: NumericDistribution | CategoricalDistribution
  outliers?: OutlierInfo
}

export interface NumericDistribution {
  bins: number[]
  counts: number[]
}

export interface CategoricalDistribution {
  labels: string[]
  counts: number[]
}

export interface OutlierInfo {
  count: number
  lower_fence: number | null
  upper_fence: number | null
  pct: number
}

export interface DataInsight {
  type: string
  severity: "info" | "warning" | "critical"
  title: string
  detail: string
}

export interface Dataset {
  id: string
  project_id: string
  filename: string
  row_count: number
  column_count: number
  uploaded_at: string
}

export interface UploadResponse {
  dataset_id: string
  filename: string
  row_count: number
  column_count: number
  preview: Record<string, unknown>[]
  column_stats: ColumnStat[]
  insights: DataInsight[]
}

/** Recharts-compatible chart configuration generated by the backend */
export interface ChartSpec {
  chart_type: "bar" | "line" | "histogram" | "scatter" | "pie"
  title: string
  data: Record<string, unknown>[]
  x_key: string
  y_keys: string[]
  x_label: string
  y_label: string
}

export interface ChatMessage {
  role: "user" | "assistant"
  content: string
  timestamp: string
  chart?: ChartSpec  // optional chart attached to assistant message
}

export interface QueryResponse {
  question: string
  answer: string
  chart_spec: ChartSpec | null
  result_rows: Record<string, unknown>[]
}

// ---------------------------------------------------------------------------
// Feature Engineering
// ---------------------------------------------------------------------------

export interface FeatureSuggestion {
  id: string
  column: string
  transform_type:
    | "date_decompose"
    | "log_transform"
    | "one_hot"
    | "label_encode"
    | "bin_quartile"
    | "interaction"
  title: string
  description: string
  preview_columns: string[]
  example_values: (string | number | null)[]
}

export interface FeatureSetResult {
  feature_set_id: string
  column_mapping: Record<string, string[]>
  new_columns: string[]
  total_columns: number
  preview: Record<string, unknown>[]
}

export interface TargetResult {
  dataset_id: string
  target_column: string
  problem_type: "classification" | "regression" | null
  reason: string
  classes: string[]
}

export interface FeatureImportanceEntry {
  column: string
  importance: number
  importance_pct: number
  rank: number
  description: string
}

export interface FeatureImportanceResult {
  dataset_id: string
  target_column: string
  problem_type: string
  features: FeatureImportanceEntry[]
}

// ---------------------------------------------------------------------------
// Model Training (Phase 4)
// ---------------------------------------------------------------------------

export interface ModelRecommendation {
  algorithm: string
  display_name: string
  description: string
  reason: string
  hyperparameters: Record<string, unknown>
}

export interface ModelMetrics {
  accuracy?: number
  f1?: number
  precision?: number
  recall?: number
  roc_auc?: number
  r2?: number
  mae?: number
  rmse?: number
}

export interface ModelRun {
  id: string
  project_id: string
  dataset_id: string
  feature_set_id?: string | null
  algorithm: string
  display_name: string
  target_column: string | null
  problem_type: string | null
  metrics: ModelMetrics | null
  training_duration_ms: number | null
  is_selected: boolean
  status: "done" | "failed"
  created_at: string
}

export interface ModelRanking {
  id: string
  algorithm: string
  display_name: string
  metrics: ModelMetrics | null
  training_duration_ms: number | null
  is_selected: boolean
  rank: number
}

export interface ModelComparison {
  summary: string
  best_model_id: string | null
  primary_metric: string
  rankings: ModelRanking[]
}

export interface RecommendResponse {
  project_id: string
  dataset_id: string
  target_column: string
  problem_type: string
  problem_type_reason: string
  recommendations: ModelRecommendation[]
}

export interface TrainResponse {
  runs: ModelRun[]
  problem_type: string
}

// ---------------------------------------------------------------------------
// Validation & Explainability (Phase 5)
// ---------------------------------------------------------------------------

export interface MetricWithCI {
  mean: number
  std: number
  ci_low: number
  ci_high: number
  fold_scores: number[]
}

export interface ConfusionMatrixAnalysis {
  type: "confusion_matrix"
  labels: string[]
  matrix: number[][]
  test_accuracy: number
  per_class_accuracy: Record<string, number>
}

export interface ResidualsAnalysis {
  type: "residuals"
  actual: number[]
  predicted: number[]
  residuals: number[]
  mae: number
  rmse: number
}

export type ErrorAnalysis = ConfusionMatrixAnalysis | ResidualsAnalysis

export interface ValidationResult {
  model_run_id: string
  algorithm: string
  display_name: string
  target_column: string | null
  problem_type: string
  n_rows: number
  n_folds: number
  metrics: Record<string, MetricWithCI>
  error_analysis: ErrorAnalysis
  limitations: string[]
}

export interface ImportanceFeature {
  column: string
  importance: number
  importance_pct: number
  std: number
  rank: number
}

export interface GlobalImportanceResult {
  model_run_id: string
  algorithm: string
  display_name: string
  target_column: string | null
  features: ImportanceFeature[]
  summary: string
  problem_type: string
  scoring_metric: string
}

export interface PredictionFactor {
  column: string
  original_value: string | number
  impact: number
  direction: "positive" | "negative" | "neutral"
}

export interface PredictionExplanation {
  model_run_id: string
  algorithm: string
  display_name: string
  target_column: string | null
  row_index: number
  prediction: string | number
  probability: number | null
  problem_type: string
  top_factors: PredictionFactor[]
}
